### ISSUE TITLE
Trying to use cookies with HubOAuth error

### ISSUE THREAD

**Issue by hsibyani** [harvard/cloudJHub#2]
Hello,

I feel that this issue is simple but I'm missing something important here. After I finish with the instructions and I can access the manager node and is able to login (tried both the vanilla devel. way and using Github OAuth), then I can't quite spawn new notebooks. The request is sent and a new instance is created, however, I get an error on the instance. When I open jupyter.log in the worker instance I get the following:
```

/usr/local/lib/python3.5/dist-packages/traitlets/config/configurable.py:84: UserWarning: Config option `cookie_name` not recognized by `HubOAuth`.
  self.config = config
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'oauth_client_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1364, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 393, in init_webapp
    self.init_hub_auth()
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 388, in init_hub_auth
    if not self.hub_auth.oauth_client_id:
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 593, in _validate
    value = self._cross_validate(obj, value)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 599, in _cross_validate
    value = obj._trait_validators[self.name](obj, proposal)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 907, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/services/auth.py", line 439, in _ensure_not_empty
    raise ValueError("%s cannot be empty." % proposal.trait.name)
ValueError: oauth_client_id cannot be empty.
```
Please let me know if you know what's going on wrong.

**Comment by farassadek** [comment]
Hi Hassan, 
Can you send the authentication part in jupyterhub_config.py in the manger (secret data hidden) please ?
Also what version of  jupyterhub  is on the worker ? 
I believe this relates to jupyterhub last broken update (version 080), check my comment here : https://github.com/jupyterhub/wrapspawner/issues/11#issuecomment-334547661 .
I already updated the code here to use jupyterhub 0.7.2 but if the system got update then it might pick up the new jupyterhub broken version.

**Comment by hsibyani** [comment]
Hi Faras, 

I just checked, the juypterhub on the manager is 0.7.2 but the one in the worker is actually 0.8.0. Where do you specify that version? Hopefully that will be it.

I used two configs. One is the original with no ssl or any external auth. The other one using a self-signed cert and GitHub Oauth.

Here is my second jupyterhub_config.py

```
import os
import sys
import socket

# Inserts location of local code into jupyterhub at runtime.
sys.path.insert(1, '/etc/jupyterhub')

# Configuration file for Jupyter Hub

c = get_config()
c.JupyterHub.cookie_secret_file = '/etc/jupyterhub/cookie_secret'
c.JupyterHub.db_url = '/etc/jupyterhub/jupyterhub.sqlite'

############ Development Settings ###############
c.JupyterHub.log_level = "DEBUG"
c.JupyterHub.debug_proxy = False  # show debug output in configurable-http-proxy

################ Network Settings ################
# leave as-is
c.JupyterHub.proxy_api_ip = '0.0.0.0'
c.JupyterHub.hub_ip = '0.0.0.0'
# TODO-SSL: 443 is for HTTPS. Use 80 if just HTTP for development
c.JupyterHub.port = 443
# TODO-SSL: change me to False
c.JupyterHub.confirm_no_ssl = False
# TODO-SSL: uncomment me below and fill paths to SSL certificate file and key
c.JupyterHub.ssl_cert = '/etc/jupyterhub/ssl/cert.pem'
c.JupyterHub.ssl_key = '/etc/jupyterhub/ssl/key.pem'

#with open("/etc/jupyterhub/api_token.txt", 'r') as f:
    # for culler script to work without modification we need to set this value in the machine environment.
#    api_token = f.read().strip()
#c.JupyterHub.api_tokens = {api_token:"__tokengeneratoradmin"}

c.Spawner.poll_interval = 10
# In seconds. Gives JupyterHub enough time to connect to the notebook.
c.Spawner.http_timeout = 300
c.Spawner.start_timeout = 300

# Setting options_form decouples logging in from spawning a notebook instance, which is useful to avoid error
# when there is already a spawn pending for a user
c.Spawner.options_form = """
<center> You will be automatically redirected. Please hold on. Servers can take up to 2 minutes to boot up. </center>
<center> If you are not redirected within 2 minutes, click <a href="/hub/home">here</a></center>

<script>
document.getElementById("spawn_form").submit();
</script>
"""

################ Spawner Settings ################
c.JupyterHub.spawner_class = 'spawner.InstanceSpawner'
# The periodicity of checks for user activity. Value is in seconds.
c.JupyterHub.last_activity_interval = 15
# Change this to set the maximum time length between entering passwords
c.JupyterHub.cookie_max_age_days = 1
# Grant admin users permission to access all user notebook servers.
c.JupyterHub.admin_access = True
c.JupyterHub.extra_log_file = '/var/log/jupyterhub'

############# User Authenticator Settings ###############
# Production authentication option with Github. Other custom authenticators can be swapped in here.
#c.JupyterHub.authenticator_class = 'oauthenticator.LocalGitHubOAuthenticator'
c.JupyterHub.authenticator_class = 'oauthenticator.LocalGitHubOAuthenticator'
c.GitHubOAuthenticator.oauth_callback_url = "https://x.y.z.w/hub/oauth_callback"
c.GitHubOAuthenticator.client_id = "xxxxxxxxxxxx"
c.GitHubOAuthenticator.client_secret = "xxxxxxxxxxxx"

# Development authenticator
#c.JupyterHub.authenticator_class = 'noauthenticator.NoAuthenticator'
c.LocalAuthenticator.add_user_cmd=['adduser', '-q', '--gecos', '""', '--disabled-password', '--force-badname']
c.LocalAuthenticator.create_system_users = True

# Add users to the admin list, the whitelist, and also record their user ids
c.Authenticator.admin_users = admin = set()
c.Authenticator.whitelist = whitelist = set()
if os.path.isfile('/etc/jupyterhub/userlist'):
    with open('/etc/jupyterhub/userlist') as f:
        for line in f:
            if line.isspace():
                continue
            parts = line.split()
            name = parts[0]
            whitelist.add(name)
            if len(parts) > 1 and parts[1] == 'admin':
                admin.add(name)
```

**Comment by farassadek** [comment]
Your config looks good. 
I found the issue and will fix it soon (unless jupyterhub folks fix 0.8.0 issue before me then i need to fix nothing). 
Basically,  I enforced the manager to use version 0.7.2 using "jupyterhub_files/requirements_jupyterhub.txt"  file.
 I did not do the same with the worker AMI (I use my own AMI therefore I did not test this on). I let pip install the latest version , therefore each time the manager spin up a new worker out of that AMI , the instance will come up with the latest version of jupyterhub which is 0.8.0.

I will fix the code and get back to you.

**Comment by farassadek** [comment]
Hi Hassan,
This is fixed. 
You need to create a new cluster and remove the old one. Do not forget to remove the security groups and the AMI of the old cluster you created. 

I created a cloud formation templates to create jupyterhub vpc and subnets, create role, and create EC GW to run the launch cluster code.  I did not push them to this repository yet because i am still in the testing process but If you want to try them out I can send them to you. 
Hope this help.

Best, 
Faras

**Comment by farassadek** [comment]
Hi Hassan 
This issue solved and the instance spawner works with the new design of Jupyterhub8 
Faras

**Comment by farassadek** [comment]
Fix jupyterhub instance spawner with the jupyterhub 8 OAuth
